var _util = require('util')
var _cart={
	addCart:function(data,success,error){
		_util.request({
			type:'post',
			url:'cart/',
			data:data,
			success:success,
			error:error
		})		
	},
	getCartCount:function(success,error){
		_util.request({
			url:'cart/count',
			success:success,
			error:error
		})		
	},
	getCart:function(success,error){
		_util.request({
			url:'cart/',
			success:success,
			error:error
		})		
	},
	selectOne:function(data,success,error){
		_util.request({
			type:'put',
			url:'cart/selectOne',
			data:data,
			success:success,
			error:error
		})		
	},
	unselectOne:function(data,success,error){
		_util.request({
			type:'put',
			url:'cart/unselectOne',
			data:data,
			success:success,
			error:error
		})		
	},
	selectAll:function(success,error){
		_util.request({
			type:'put',
			url:'cart/selectAll',
			success:success,
			error:error
		})		
	},
	unselectAll:function(success,error){
		_util.request({
			type:'put',
			url:'cart/unselectAll',
			success:success,
			error:error
		})		
	},
	deleteOne:function(data,success,error){
		_util.request({
			type:'put',
			url:'cart/deleteOne',
			data:data,
			success:success,
			error:error
		})		
	},
	deleteSelected:function(success,error){
		_util.request({
			type:'put',
			url:'cart/deleteSelected',
			success:success,
			error:error
		})		
	},
	updateCount:function(data,success,error){
		_util.request({
			type:'put',
			url:'cart/updateCount',
			data:data,
			success:success,
			error:error
		})		
	},				
}

module.exports = _cart